### ISSUE TITLE
ImportError: No module named cpuset.main

### ISSUE THREAD

**Issue by reginaldo-junior** [lpechacek/cpuset#41]
root@reginaldo-junior:/home/reginaldojunior/Documentos/UFscar/cpuset# python3.6 setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/bin/cset to 755
running install_data
running install_egg_info
Removing /usr/lib/python3.6/site-packages/cpuset-1.6-py3.6.egg-info
Writing /usr/lib/python3.6/site-packages/cpuset-1.6-py3.6.egg-info
root@reginaldo-junior:/home/reginaldojunior/Documentos/UFscar/cpuset# /usr/bin/cset
Traceback (most recent call last):
  File "/usr/bin/cset", line 44, in <module>
    from cpuset.main import main
ModuleNotFoundError: No module named 'cpuset'

**Comment by Werkov** [comment]
Thanks for the report.
(I'm not a python3 module resolution expert but) 
Can you share the output of `python3 -c "import sys; print(sys.path, sys.prefix)"` and `python3 -c "import sys; print(sys.path, sys.prefix)"`?
(You seem to install the package into python3 directory but the `cset` would use `python` which may default to python2 (without the cpuset module).)

**Comment by reginaldo-junior** [comment]
Sure!

My output for commands is:

```
 python3 -c "import sys; print(sys.path, sys.prefix)"
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/reginaldojunior/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages'] /usr
```

```
python3 -c "import sys; print(sys.path, sys.prefix)"
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/reginaldojunior/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages'] /usr
```

I tried install for python2.7 too, but has same error:

```
/usr/bin/cset 
Traceback (most recent call last):
  File "/usr/bin/cset", line 44, in <module>
    from cpuset.main import main
ImportError: No module named cpuset.main
```

Start file /usr/bin/cset is header on python2.7

```
cat /usr/bin/cset 
#!/usr/bin/python2.7

__copyright__ = """
Copyright (C) 2007-2010 Novell Inc.
Author: Alex Tsariounov <tsariounov@gmail.com>

....

```

**Comment by Werkov** [comment]
> Start file /usr/bin/cset is header on python2.7

That is interesting, the [upstream version](https://github.com/lpechacek/cpuset/blob/v1.6/cset#L1) uses resolution via `env`.
What (source) version are you using? (Is that your distro's downstream patch?)
If your distro uses python2.7, you may try installing with `python2.7 setup.py install` (just an idea).

(I apology, I made a copy-paste-edit error in my request comment -- I asked about python3 two times.) But from what you've posted, the `/usr/lib/python3.6/site-packages/` is missing in `sys.path`.

**Comment by reginaldo-junior** [comment]
Hello! Thanks.

Still not solve :( 

I'm installing using python2.7 how mentioned, but same error ocorred.

```root@reginaldo-junior:/home/reginaldojunior/Documentos/UFscar/cpuset# python2.7 setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/bin/cset to 755
running install_data
running install_egg_info
Removing /usr/lib/python2.7/site-packages/cpuset-1.6-py2.7.egg-info
Writing /usr/lib/python2.7/site-packages/cpuset-1.6-py2.7.egg-info
root@reginaldo-junior:/home/reginaldojunior/Documentos/UFscar/cpuset# cset
Traceback (most recent call last):
  File "/usr/bin/cset", line 44, in <module>
    from cpuset.main import main
ImportError: No module named cpuset.main
root@reginaldo-junior:/home/reginaldojunior/Documentos/UFscar/cpuset# cat /usr/bin/cset 
#!/usr/bin/python2.7

__copyright__ = """
Copyright (C) 2007-2010 Novell Inc.
Author: Alex Tsariounov <tsariounov@gmail.com>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License version 2 as
published by the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

---------------------------------------------------------------------
Substrate code and ideas taken from the excellent stgit 0.13, see
  https://gna.org/projects/stgit  and  http://www.procode.org/stgit/
Stacked GIT is under GPL V2 or later.
---------------------------------------------------------------------
"""

import sys, os

# Try to detect where it is run from and set prefix and the search path.
# It is assumed that the user installed cpuset using the --prefix= option
prefix, bin = os.path.split(sys.path[0])

if bin == 'bin' and prefix != sys.prefix:
    sys.prefix = prefix
    sys.exec_prefix = prefix

    major, minor = sys.version_info[0:2]
    local_path = [os.path.join(prefix, 'lib', 'python'),
                  os.path.join(prefix, 'lib', 'python%s.%s' % (major, minor)),
                  os.path.join(prefix, 'lib', 'python%s.%s' % (major, minor),
                               'site-packages')]
    sys.path = local_path + sys.path

from cpuset.main import main

if __name__ == '__main__':
    main()
```

**Comment by Werkov** [comment]
@reginaldo-junior As I saw you progressed beyond python module loading (in #42), is _this_ issue still relevant? (Honestly, I'm not convinced the python load path resolution is a bug in the cpuset itself.)

**Comment by reginaldo-junior** [comment]
Okay! Thanks. I solved install apt cpuset.
