### ISSUE TITLE
Erro the create CPU / failed to create shield, hint: do other cpusets exist

### ISSUE THREAD

**Issue by reginaldo-junior** [lpechacek/cpuset#42]
Hello, i'm try using cpuset version 1.6. But I was try init shield show this error:

"failed to create shield, hint: do other cpusets exist?"

I'm was Investigate in code, found this section where from raised erro:

```
    try:
        shield_exists()
    except:
        log.debug("shielding does not exist, creating")
        try:
            print(cpuspec)
            print(cpuspec_inv)
            set.create(USR_SET, cpuspec, memspec, True, False)
            set.create(SYS_SET, cpuspec_inv, memspec, True, False)
        except Exception as instance:
            # unroll
            try: set.destroy(USR_SET)
            except: pass
            try: set.destroy(SYS_SET)
            except: pass
            log.critical('--> failed to create shield, hint: do other cpusets exist?')
            raise instance
        log.info('--> activating shielding:')
```

I can undestand of methods creates not found cpusets from this wasn't create. I was try change of variables of hard-coded cpuspec to 0 and cpuspec_inv to 0 too, works, but not works for all cpus. How can solve this?

**Comment by Werkov** [comment]
Your report is missing what commands with what parameters did you run and what was the environment where you tried it.
Please take a look at #34 (both for a bug report example and it may also be a duplicate of your issue).

**Comment by reginaldo-junior** [comment]
Yes! The issue #34 solved my problem, thanks! :)
