### ISSUE TITLE
docs typo

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lpechacek/cpuset#8]
```
Patch submitted by Roberto Sanchez.
```

Original issue reported on code.google.com by `tsariou...@gmail.com` on 25 Sep 2011 at 12:44

Attachments:
* [cpuset_typo.diff](https://storage.googleapis.com/google-code-attachments/cpuset/issue-8/comment-0/cpuset_typo.diff)

**Comment by lpechacek** [comment]
Fixed with commit 86cb8ac7d3db.
